// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Falcor.Client")]
[assembly: AssemblyCopyrightAttribute("2015 Falcor.NET")]
[assembly: AssemblyDescriptionAttribute("Falcor.Client")]
[assembly: AssemblyProductAttribute("Falcor.NET")]
[assembly: AssemblyVersionAttribute("0.0.3")]
[assembly: AssemblyFileVersionAttribute("0.0.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.3";
    }
}
