// <auto-generated/>

using System.Reflection;

[assembly: AssemblyTitle("Falcor")]
[assembly: AssemblyCopyright("2015 Falcor.NET")]
[assembly: AssemblyDescription("Falcor")]
[assembly: AssemblyProduct("Falcor.NET")]
[assembly: AssemblyVersion("0.0.4")]
[assembly: AssemblyFileVersion("0.0.4")]
namespace Falcor.Properties {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.4";
    }
}
