// <auto-generated/>

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Falcor.Server")]
[assembly: AssemblyCopyright("2015 Falcor.NET")]
[assembly: AssemblyDescription("Falcor.Server")]
[assembly: AssemblyProduct("Falcor.NET")]
[assembly: AssemblyVersion("0.0.4")]
[assembly: InternalsVisibleTo("Falcor.Tests")]
[assembly: AssemblyFileVersion("0.0.4")]

namespace Falcor.Server.Properties
{
    internal static class AssemblyVersionInformation
    {
        internal const string Version = "0.0.4";
    }
}