// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Falcor.Server")]
[assembly: AssemblyCopyrightAttribute("2015 Falcor.NET")]
[assembly: AssemblyDescriptionAttribute("Falcor.NET router implementation. To use Falcor on the server, use the Falcor.Server.Owin package.")]
[assembly: AssemblyProductAttribute("Falcor.NET")]
[assembly: AssemblyVersionAttribute("0.1.2")]
[assembly: InternalsVisibleToAttribute("Falcor.Tests")]
[assembly: AssemblyFileVersionAttribute("0.1.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.2";
    }
}
