// <auto-generated/>

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Falcor.Examples.Netflix")]
[assembly: AssemblyCopyright("2015 Falcor.NET")]
[assembly: AssemblyDescription("Falcor.Examples.Netflix")]
[assembly: AssemblyProduct("Falcor.NET")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: InternalsVisibleTo("Falcor.Tests")]
[assembly: AssemblyFileVersion("0.1.0")]

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string Version = "0.1.0";
    }
}