// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Falcor.Examples.Netflix")]
[assembly: AssemblyCopyrightAttribute("2015 Falcor.NET")]
[assembly: AssemblyDescriptionAttribute("Falcor.Examples.Netflix")]
[assembly: AssemblyProductAttribute("Falcor.NET")]
[assembly: AssemblyVersionAttribute("0.0.7")]
[assembly: InternalsVisibleToAttribute("Falcor.Tests")]
[assembly: AssemblyFileVersionAttribute("0.0.7")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.7";
    }
}
