// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Falcor.Examples.NetflixWeb")]
[assembly: AssemblyCopyrightAttribute("2015 Falcor.NET")]
[assembly: AssemblyDescriptionAttribute("Falcor.Examples.NetflixWeb")]
[assembly: AssemblyProductAttribute("Falcor.NET")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: InternalsVisibleToAttribute("Falcor.Tests")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
    }
}
