// <auto-generated/>

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Falcor.Examples.NetflixWeb")]
[assembly: AssemblyCopyright("2015 Falcor.NET")]
[assembly: AssemblyDescription("Falcor.Examples.NetflixWeb")]
[assembly: AssemblyProduct("Falcor.NET")]
[assembly: AssemblyVersion("0.0.6")]
[assembly: InternalsVisibleTo("Falcor.Tests")]
[assembly: AssemblyFileVersion("0.0.6")]
namespace Falcor.Examples.NetflixWeb.Properties {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.6";
    }
}
